// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqa2Ki0JPR1IQ1B0PkGljrwVlQX33Wjt0',
    appId: '1:32866254432:web:7b506cce91781127d38d05',
    messagingSenderId: '32866254432',
    projectId: 'honorata-a81ba',
    authDomain: 'honorata-a81ba.firebaseapp.com',
    storageBucket: 'honorata-a81ba.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6_RzG3cGE5_xdl9GBK-lEuS4gnyXUDHA',
    appId: '1:202765333893:ios:a5760db3915731850080ec',
    messagingSenderId: '202765333893',
    projectId: 'appmenumw',
    storageBucket: 'appmenumw.firebasestorage.app',
    iosBundleId: 'com.example.appWeb1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqa2Ki0JPR1IQ1B0PkGljrwVlQX33Wjt0',
    appId: '1:32866254432:web:40fcfe0134845410d38d05',
    messagingSenderId: '32866254432',
    projectId: 'honorata-a81ba',
    authDomain: 'honorata-a81ba.firebaseapp.com',
    storageBucket: 'honorata-a81ba.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCocw6NThMZ9ND2ms2F8ftzYB3p_XAs7kU',
    appId: '1:32866254432:android:4193b4fa8287094bd38d05',
    messagingSenderId: '32866254432',
    projectId: 'honorata-a81ba',
    storageBucket: 'honorata-a81ba.firebasestorage.app',
  );
}
